### ISSUE TITLE
- Góp ý:

### ISSUE THREAD

**Issue by vfa-namth** [vfa-trongvn/JavaScript-Standard-Style#1]
- Em nên nói mình sẽ áp dụng cho ES5 hay ES6. Hiện tại anh thấy chỉ áp dụng được ES6.
- Chưa thấy chuẩn đặt tên, biến, function, class...
- DRY – Don’t Repeat Yourself.

**Comment by vfa-trongvn** [comment]
Em đã update:
https://github.com/vfa-trongvn/JavaScript-Standard-Style/commit/ccf3a53a16bb463b9c3157719a23ea4538bf9497

**Comment by vfa-anhtq** [comment]
Confirmed
