### ISSUE TITLE
Cần thêm phần đánh giá performance và lean code khi review

### ISSUE THREAD

**Issue by vfa-anhtq** [vfa-trongvn/JavaScript-Standard-Style#2]
anh TrungBB said:
> Anh thấy cũng ổn nhưng thiếu phần liên quan đến performance cả 2 phần .

> hay kiẻu viết rườm rà ... 
ví dụ  : 
```
if ( userController.removeUserInfo() && userController.saveUserInfo(info: info)) {
             return true
         }
         return false
```

**Comment by vfa-trongvn** [comment]
Em đã update, nhờ anh review lại. 
https://github.com/vfa-trongvn/JavaScript-Standard-Style/commit/a3780cf7b55319b3412d6b6aa5316c8ca6700a1e

**Comment by vfa-anhtq** [comment]
Confirmed
